### ISSUE TITLE
Supporting UTF-8 charz on Opera browser

### ISSUE THREAD

**Issue by morilog** [lauriro/json-lite#1]
This extension does not support UTF-8 characters on opera browser.
my opera is version 42.0.

![screenshot from 2016-12-21 15-40-28](https://cloud.githubusercontent.com/assets/4139179/21388931/19f84b7c-c794-11e6-957e-fca7057183b3.png)

**Comment by lauriro** [comment]
This extension displays json as it is received from backend, without unescaping anything.

Your backend escapes Unicode characters.

I am not sure, would it be a good idea to unescape result as it would make difficult to understand, what actually received from backend. Maybe an unescaped title or something could be helpful.

**Comment by morilog** [comment]
escaped result is a Farsi text, Other json view extensions works well on every browser even on opera except json-lite.  
BTW, i installed another extension for formatting json responses.

**Comment by lauriro** [comment]
Although it is probably not good for you,
in version 0.18 context menu there are option to unescape selected text.

As a developer I still prefer to see actual response from backend
so I could fix unnecessary escapes (json does not require to escape unicode).
