### ISSUE TITLE
Autodetect links

### ISSUE THREAD

**Issue by alexduf** [lauriro/json-lite#12]
Great extension, I just had an idea.

It would be great if it could detect http and https links in the data so a simple click could allow a user to navigate through a JSON API for instance.

I know JsonView used to do that but it's not compatible with firefox 57+

**Comment by lauriro** [comment]
Do you mean links inside a longer texts? Links as values should be detected.

**Comment by alexduf** [comment]
Then it looks like I have a bug on my side?
if you look at this API for instance: https://mobile.guardianapis.com/uk/navigation

I have the result hereafter and can't click on the uri:

![screenshot from 2017-10-12 16-58-56](https://user-images.githubusercontent.com/3389563/31506210-b557f7bc-af6e-11e7-97b1-6adb9be22258.png)

**Comment by lauriro** [comment]
According to the picture you are using different json viewer or [Firefox native JSON viewer](https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer).

Native viewer can be disabled by toggling 'devtools.jsonview.enabled' flag in about:config page.

**Comment by alexduf** [comment]
Oh my!
Apologies for the time loss 🙄

**Comment by alexduf** [comment]
What's interesting is that no formatting was done until I install your extensions, then got that.
I just tried to disable it and I still get the formatting. It's almost as if the mime type wasn't triggering anything unless the extension was here.

I'm using firefox 57 beta so who knows, maybe something isn't quite right.

**Comment by alexduf** [comment]
If anyone falls into the same pitfall as I did: about:config, change the property devtools.jsonview.enabled to false.

Then you can start using this extension.
