### ISSUE TITLE
Configure Response Content Type

### ISSUE THREAD

**Issue by chet20r** [lauriro/json-lite#13]
On **Firefox v56.0**, when browsing spring boot applications, the response content type is `application/vnd.spring-boot.actuator.v1+json;charset=UTF-8` and is not recognized by the plugin as a JSON. Need a way to configure response mime types in the plugin so that the response can be interpreted correctly

**Comment by lauriro** [comment]
This extension does not look content type and should work with any content type.
To check that this extension is in use, see #12.

**Comment by chet20r** [comment]
Thanks for your reply. The json view settings in firefox is already disabled
![image](https://user-images.githubusercontent.com/7542319/32436663-85c55bd6-c330-11e7-938a-eb774e88808a.png)

This is what I get when I try to access a spring boot api endpoint
![image](https://user-images.githubusercontent.com/7542319/32436714-a8a94a40-c330-11e7-9e19-cf244682e9af.png)

and I have the jsonlite plugin installed and enabled
![image](https://user-images.githubusercontent.com/7542319/32436766-d5b3e8f6-c330-11e7-8d19-8a3033189869.png)

**Comment by ractive** [comment]
You can install the [json-mime-type-override](https://addons.mozilla.org/de/firefox/addon/json-content-type-override/) extension so that all json content types are always rewritten to `application/json` - which makes json-lite work as well with spring boot actuator endpoints.

**Comment by chet20r** [comment]
@ractive 's suggestion of adding a mime type override plugin to firefox worked. Now jsonlite renders spring actuator endpoints correctly. Although not ideal, but it works. Kudos to @lauriro  for building such a light and elegant json viewer plugin.
