### ISSUE TITLE
Doesn't work with data: uri pages

### ISSUE THREAD

**Issue by chowells79** [lauriro/json-lite#14]
Sometimes I want to quickly view some json data formatted nicely.  I throw it into my browser with a `data:` uri, something like `data:application/json,{"productId":0,"viewLink":"string"}`. json-lite doesn't format the page.

This is observed in FireFox 57 and Chrome 61

**Comment by lauriro** [comment]
I have no idea, how to access data uris using WebExtension.

**Comment by lauriro** [comment]
At my current knowledge, it is not possible to access data uris with webextension.
This is not doable. Reopen when there are options.
