### ISSUE TITLE
Move the opener/collapser symbols to the left, please

### ISSUE THREAD

**Issue by halmai** [lauriro/json-lite#16]
If I have a JSON like this:

```

{
    "short": [ V 3 items, 10 bytes
        1,
        2,
        3
    ],
    "very-very-very-very-long": [  V 3 items, 30 bytes
        1,
        2,
        3
    ]
}
```

then opening/closing the individual substructures requires positioning the mouse to the end of each line. This is hard because the length of the lines is changing.

Instead of this, I would like to have the opener/collapser symbol in the front of each structure, like this:

```

{
    V "short": [ 3 items, 10 bytes
        1,
        2,
        3
    ],
    V "very-very-very-very-long": [  V 3 items, 30 bytes
        1,
        2,
        3
    ]
}
```

**Comment by lauriro** [comment]
This would probably require a greater design change,
something similar to IntelliJ IDEA as shown in #2.
