### ISSUE TITLE
Manifest issues

### ISSUE THREAD

**Issue by icl7126** [lauriro/json-lite#18]
I can see some errors in your manifest file in about:debugging page. You may want to fix these :)

> Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
> Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

**Comment by icl7126** [comment]
I'm not so sure. There are more differences in manifest files, for example the Firefox specific (I'm not sure how can this be even loaded in Chrome):
`"applications": {
    "gecko": {
      "id": "{16a49f65-1369-4839-a5ef-db2581e08b16}"
    }
}`
Also maintaining two manifest files where only change you ever do is changing the version number seems fine. You can also use custom build script that will generate those files, it's just JSON.

Anyway seeing error message next to the add-on doesn't look very professional so I would fix it just because of that :). But I get it, spending time with something that doens't really bring new features sucks.

**Comment by lauriro** [comment]
Browser Extensions are meant to be interoperable across browsers.
As Firefox and Chrome both introduces custom properties in manifest and warns about unexpected properties - I think that propper solution should be to file a bug for Firefox and Chrome :p 

You are right about cost on maintaining separated manifests vs warnings - will fix in next release but no extra release for that.

**Comment by lauriro** [comment]
> Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

For that one there are bug reported https://bugzilla.mozilla.org/show_bug.cgi?id=1370077
