### ISSUE TITLE
Firefox - Blank screen

### ISSUE THREAD

**Issue by OrangutanGaming** [lauriro/json-lite#19]
With the plugin enabled on Firefox 57, it's just giving me a white screen. I have disabled the built in one, but there's still no difference. I'm using https://jsonview.com/example.json which works fine normally, however, even though using the inspector I can see the JSON still exists, it's not showing anything

**Comment by lauriro** [comment]
Any error in console?
Any other extension installed?
Try again when all other extensions are disabled. If it works then, enable other extensions one by one and test each one to find out - does some extensions conflicts.

**Comment by OrangutanGaming** [comment]
No errors in console.
Doesn't work with all extensions off.

**Comment by lauriro** [comment]
I am not able to reproduce the issue and there are not enough information to investigate further.

Try to:
 - reinstall extension
 - restart your browser
 - test with a new clean firefox profile
 - follow [Add-on Debugging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging)

**Comment by OrangutanGaming** [comment]
For some reason, the first 3 didn't do anything, but as soon as I opened the debugger and refreshed, it worked, and it's working fine now
