### ISSUE TITLE
Add support for JSONAPi content type

### ISSUE THREAD

**Issue by luispabon** [lauriro/json-lite#20]
Currently, Firefox doesn't recognise JSONAPI as json and offers a download instead of displaying. I'm wondering whether it'd be possible for json lite to recognise the format as JSON and display as normal.

The content type is `application/vnd.api+json`

**Comment by lauriro** [comment]
Same issue with a workaround was in #13
I am not decided yet, should this be implemented in json-lite or is separated extension better.

**Comment by luispabon** [comment]
It'd make  json-lite have no dependencies in order to work with these content types, I reckon that'd be a good thing
