### ISSUE TITLE
More user friendly settings

### ISSUE THREAD

**Issue by Ajnasz** [lauriro/json-lite#23]
I think it would be more user friendly if we would replace the input where user can enter CSS with `input type="color"`. Also introduce a few checkboxes for bold and italic and maybe something for text-shadow (however I would not stick to shadow, but it's there now :) ).
If you think it's a good idea, I would like to help to implement it.

**Comment by lauriro** [comment]
With a tool for developers I am more comfortable with a full-featured text inputs. Same functionality would be hard to implement in reasonable amount code.
Lot of developers are bad in choosing colors anyway.

I think it would be more useful to craft a couple more good looking themes (dark, contrast, etc) and for rare fine tuning `input type=text` is good enough.

**Comment by Ajnasz** [comment]
To create themes, what if we set change the CSS class names to constants, for example `json-lite-property-name`, `json-lite-number` and so on, and then anyone can write plain css and use [Stylus](https://add0n.com/stylus.html) or userchrome.css to apply a theme.

**Comment by lauriro** [comment]
I think added value would not be great enough, themes can be used already.
