### ISSUE TITLE
Display of json which uses JSON hijacking protection

### ISSUE THREAD

**Issue by derak-kilgo** [lauriro/json-lite#24]
Firefox 58

I've encountered json response which is supposed to prevent hijacking as described here:
https://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses#2669766

When decoding these responses; the plug-in displays:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

In raw view, you can see:
while(1);[{"created_at":"2017-1...

Would it be possible to adapt this plug-in to display json "protected" in this manner?

**Comment by derak-kilgo** [comment]
Found the line in the readme:

Disable Firefox built in JSON viewer
Go to about:config and set 'devtools.jsonview.enabled' to false

Your viewer displays these correctly. Thanks.

**Comment by lauriro** [comment]
#12
