### ISSUE TITLE
Add option to default to open/colapsed

### ISSUE THREAD

**Issue by grgrssll** [lauriro/json-lite#26]
- Report a *bug* with browser version 

Firefox extension version 17.12.2

It doesn't make sense to me (perhaps it does to others) that it would default to having everything collapsed on load. Can you add an option in the preferences to default to having all objects/arrays non collapsed (long strings seems fine to default to collapsed).

[This is what it looks like when I load a json document ](https://imgur.com/a/eLjhl ). It really sucks having to open all of the things everytime I load the document... In fact I hate it and wish JSONview still worked in the latest version of FF

**Comment by lauriro** [comment]
According to the picture you are using different json viewer or Firefox native JSON viewer.

Native viewer can be disabled by toggling 'devtools.jsonview.enabled' flag in about:config page.
