### ISSUE TITLE
doesn't work for 'file://' URLS

### ISSUE THREAD

**Issue by slchorne** [lauriro/json-lite#29]
If you open a json file with a 'file://' URL the renderer doesn't work at all.
I don't know if this is a safari limitation, or the plugin

**Comment by lauriro** [comment]
In Chrome there is an option 'Allow access to file URLs' for extension in chrome://extensions page.

[First](http://livereload.com/use-cases/local-files/) [results](https://discussions.apple.com/thread/2747354) from google suggest that this is not possible is safari. At the moment I do not have an access to osx.

**Comment by lauriro** [comment]
I have an untested idea, that global background page works with file urls, just content script is not injected.
So maybe it is possible to inject content script from background.

**Comment by lauriro** [comment]
last idea did not worked out, not doable by current knowledge
