### ISSUE TITLE
Feature request: automatically hyperlink URLs

### ISSUE THREAD

**Issue by dregad** [lauriro/json-lite#30]
I started using JSON lite after upgrading Firefox to v57, because the Add-on I was using until now ([JSONview](https://jsonview.com/)) is not compatible with WebExtensions. There is one functionality that I miss: automatically hyperlinked URLs.

It would be great if you would consider adding detection of URLs in string data, and turn them into links.

Thanks for developping this tool !

**Comment by lauriro** [comment]
Do you mean urls in the middle of longer strings?
Currently, if the entire string is url, it should be clickable.

**Comment by dregad** [comment]
@lauriro thanks for the prompt reply. 
> Do you mean urls in the middle of longer strings?

No, the entire string is an URL

> if the entire string is url, it should be clickable

Sorry but I don't see any link...
![image](https://user-images.githubusercontent.com/449891/35099469-6458c6de-fc58-11e7-9949-72f00d4959c5.png)
This is the relevant extract from the raw JSON
```json
{"nom":"Wifi","libelle":"Points Wifi","type_flux":"wifi","url_icone":"http:\/\/xxxxxxxx\/fileadmin\/xxxxxxxx\/templates\/images\/iparc\/icone\/__resolution__\/plan_wifi.png","url_flux":"http:\/\/xxxxxxxx\/themes\/environnement-urbain-espaces-verts\/espaces-verts\/iparc\/wifi\/wifis\/listWifis\/json\/typeWifi\/","date_maj":"2017-08-04"}
```
Note: I also tried without the escaped slashes (i.e. replaced `\/` by `/` in the URL strings), same results

**Comment by lauriro** [comment]
According to the picture you are using different json viewer or [Firefox native JSON viewer](https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer).

Native viewer can be disabled by toggling 'devtools.jsonview.enabled' flag in about:config page.

**Comment by dregad** [comment]
Duh. I did not even realize that... Thanks for enlightening me ! 

I confirm that after setting `devtools.jsonview.enabled` to false, I can now click the URL links. Thanks ! 

As a suggestion to avoid such situation in the future, maybe there could be a warning in the plugin's config page when the Firefox default JSON viewer is enabled.
