### ISSUE TITLE
Extension error: TypeError: items is undefined

### ISSUE THREAD

**Issue by bgehman** [lauriro/json-lite#32]
Firefox ESR 52.5.1 (64-bit) with Json Lite v18.1.0

See following error in FF console when trying to open a JSON file with this plugin enabled:
```
Extension error: TypeError: items is undefined moz-extension://c6e28001-95ab-43ff-82f7-e90862da3f68/background.js 78
[[Exception stack
onGot@moz-extension://c6e28001-95ab-43ff-82f7-e90862da3f68/background.js:78:10
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:73:129
runSafeWithoutClone@resource://gre/modules/ExtensionCommon.jsm:133:38
wrapPromise/</<@resource://gre/modules/ExtensionCommon.jsm:322:15
withLastError@resource://gre/modules/ExtensionCommon.jsm:262:14
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:316:11
]]
```

Browser window stays blank.  `devtools.jsonview.enabled` is set to `false` in about:config.

**Comment by lauriro** [comment]
I see one more line

> Unchecked lastError value: Error: Please set webextensions.storage.sync.enabled to true in about:config  ExtensionCommon.jsm:265

[Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1331179)
