### ISSUE TITLE
Add a toggle button

### ISSUE THREAD

**Issue by eternalstarfire** [lauriro/json-lite#33]
A toggle button would be a nice feature so that the pretty JSON formatting can be quickly toggled on or off without needing to go to the Add-on settings and disable it globally.

**Comment by lauriro** [comment]
Although this is not a solution, currently you can disable auto-format in options and format only desired responses by clicking JSON Lite icon.

Will think about it how to make it more friendly. First thought is to make JSON Lite icon to toggle between formatet and plain output and remember last decision.

**Comment by eternalstarfire** [comment]
> ... currently you can disable auto-format in options and format only desired responses by clicking JSON Lite icon.

This workaround sounds good... but I am using Firefox 58.0.2 640bit on Win7 and I cannot see any JSON Lite icon :disappointed: 
I have other addons with icons, but JSON Lite (18.2.0) icon is missing despite the adding being enabled and working well. It is not one of the available icons in the 'Customise...' menu either.
Any tips? Can you reproduce this on Firefox?

**Comment by lauriro** [comment]
A [pageAction](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/pageAction) should appear when you set JSON Lite option Auto-format documents off and visit a page with json content.

**Comment by shravan2x** [comment]
This would be a useful feature to have, any progress?
