### ISSUE TITLE
Decode feature?

### ISSUE THREAD

**Issue by AurevoirXavier** [lauriro/json-lite#35]
Awesome plugin, but sometimes I want to see the word instead of the unicode (`\uxxxx`).

What should I do?

**Comment by AurevoirXavier** [comment]
Btw, if it support auto linefeed that will be much better.

**Comment by lauriro** [comment]
Option a) select unicode (`\uxxxx`) with mouse and select "JSON Lite"->Decode->Unicode under right click.
Option b) select "Auto-unescape strings" in JSON Lite settings.

The part about auto linefeed i did not understand.

**Comment by AurevoirXavier** [comment]
I'm Safari user, I can't find the  **JSON Lite** or **Decode** option.

And sorry for my expression, I mean some field which have a long content that should be show in a newline. 

![img](https://i.imgur.com/yKggSPp.jpg)

**Comment by lauriro** [comment]
Safari port is very old and I dont have access to osx.
I wrote some ideas to safari branch without testing.

Maybe one day I find time to make my macbook dualboot and install osx back :p

**Comment by lauriro** [comment]
there is a new release for testing https://www.litejs.com/pub/json-lite-18.2.0.safariextz

**Comment by AurevoirXavier** [comment]
Oh, thanks for your hard work!

It works great!

There's a little problem, only the **unescaped strings** can be format, the long url still out of the screen.

**Comment by lauriro** [comment]
there is a new release for testing https://www.litejs.com/pub/json-lite-18.2.1.safariextz

**Comment by AurevoirXavier** [comment]
All features work correctly!

It's the best json plugin I have ever see, thanks.

**Comment by Grossdm** [comment]
@lauriro , perhaps @AurevoirXavier meant something like "word strap" when he wrote "auto linefeed"?

Doug®

**Comment by AurevoirXavier** [comment]
Hey, I update to Mojave today and Safari don't allow to install extension outside the official website. Could you upgrade the [it](https://safari-extensions.apple.com/details/?id=com.litejs.json-lite-YVKYWJZ9CZ)?  :)
