### ISSUE TITLE
Extension stopped working in Opera 56.0.3051.52

### ISSUE THREAD

**Issue by Ariandr** [lauriro/json-lite#38]
After the latest Opera update the extension stopped formatting JSON on pages. I tried reinstalling it, relaunching Opera and so on. Nothing helped. Works well in Chrome though.
I use the extension every day and I'd appreciate the fix. Thank you!

**Comment by Ariandr** [comment]
Sorry, extension didn't work because of Google™ Translator extension. My bad. :)

**Comment by lauriro** [comment]
Try git version with translation extension

Lauri.

-- sent from phone

Saatja Aleksandr Honcharov <notifications@github.com kirjutas kuupäeval R,
2. november 2018 16:32 järgmist:
