### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by rooftopsparrow** [lauriro/json-lite#4]
🎉 👍 💯 

This has been a much needed extension in Safari for ages. You've done Safari users everywhere a HUGE favor. If you accept donations or need anything, please let me know!

**Comment by lauriro** [comment]
Thank you! I made this extension as I needed it and I am happy when someone else also find it useful.

**Comment by lauriro** [comment]
Help with safari port is needed :) #35 #29

**Comment by rooftopsparrow** [comment]
I'll see what I can do 👍

**Comment by lauriro** [comment]
I got something done, not complete port but good enough for me at the moment 🍺 
Themes are missing and settings are implemented by Settings.plist, not options.html - small issues
