### ISSUE TITLE
Does not work anymore for applicaiton/hal+json

### ISSUE THREAD

**Issue by sabi0** [lauriro/json-lite#47]
I had everything working fine in Firefox 66.0.5 for our internal service that returns application/hal+json.
Then I upgraded to Firefox 67. And of course did not make a backup of the profile.

The add-on stopped working. And I cannot get it working again even after downgrading Firefox back to 66.0.5.
I just see JSON in plain text.

When I refresh the tab where the add-on is supposed to kick in I get this error message in the browser console: Error: WebExtension context not found!
Other JSON viewers (JSONView, MJsonViewer) have no problem displaying this tab's application/hal+json content.

P.S. I am going to stay with Firefox 66 for now. As 67 introduced a couple of backward incompatibilities I cannot put up with.

**Comment by sabi0** [comment]
I also have json-mime-type-override add-on installed.
Can't remember if it was needed for JSON Lite. Or if I installed it for some other purpose.
But the two do not seem to work together anymore.

**Comment by lauriro** [comment]
I am not able to reproduce any error in Firefox 67.0, everything works fine.
json-content-type-override is not needed for this extension,
although I installed it and they worked together.

**Comment by lauriro** [comment]
Try to change the auto-format documents setting

**Comment by sabi0** [comment]
I can't check it right now. I could only let you know if it helped in a
couple of weeks.

Feel free to close the ticket if you prefer not to keep it open for so long.

**Comment by sabi0** [comment]
Changing the "Auto-format documents" option did help. Thank you.
It was blank. And after I set it to "under 1 MB" everything works fine again.
