### ISSUE TITLE
Does not working

### ISSUE THREAD

**Issue by aisen0921** [lauriro/json-lite#48]
Firefox:67.0
`devtools.jsonview.enabled` set to `false`
Reinstall extension.

But still not working.
Someone can help me?
Thanks.

**Comment by lauriro** [comment]
run Firefox with ProfileManager option `firefox -ProfileManager` and try a new profile.

**Comment by aisen0921** [comment]
> run Firefox with ProfileManager option `firefox -ProfileManager` and try a new profile.

Use new profile is fine, but when I sync firefox the problem is occurrence again,
I need my password and history..., how can I fix it?

**Comment by aisen0921** [comment]
I found the reason is the auto-format documents of setting default is empty,
select a option can resolved this problem.

**Comment by lauriro** [comment]
Thank you, I will investigate, what have been changed in loading settings.
