### ISSUE TITLE
Parsing error when json string contains html escaped characters

### ISSUE THREAD

**Issue by DanielVukelich** [lauriro/json-lite#52]
Bug:
Loading a json string that contains html-escaped characters like `&quot;` causes the parser to error out with the message: 
`SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line X column Y of the JSON data`

How to reproduce:

- Make a file called `foo.html` in a folder on your computer.
- Put the following text inside the new file: `{ "status" : "OK&quot;", "message" : {}}`
- Open `foo.html` with your browser
- The loaded webpage now contains a message referring to syntax errors, and the "message" part of the json is now highlighted in red

Expected behavior:
`foo.html` should load with no errors

Browsers tested on:
Firefox developer edition 78.0b8, Debian 8
Plugin version: 19.6.0

**Comment by lauriro** [comment]
`json-lite` works after document load and browser has unescaped `&quot;` before loading it.
This html shows `{ "status" : "OK"", "message" : {}}` when `json-lite` is disabled and this is what extension will get.

I have no idea how to get raw source from html, you should use json file extension.
