### ISSUE TITLE
Copy and paste does not preserve the original indentation 

### ISSUE THREAD

**Issue by PaulNovodonSWM** [lauriro/json-lite#53]
Observed in Firefox 77.

Reproduce steps:
1. Copy a selection of a formatted JSON (make sure it contains indentation for the enclosed children objects)
2. Go to a text editor (any would do; mine were BBEdit on Mac and Notepad++ on Win)
3. Paste the selection
4. Observe that the indentation is lost and all lines start from the beginning (see attached images)

Original JSON selection:

<img width="339" alt="Screen Shot 2020-07-07 at 15 08 19" src="https://user-images.githubusercontent.com/60126381/86715777-e6851c80-c063-11ea-880e-dfebb51e99f9.png">

Pasted selection:

<img width="356" alt="Screen Shot 2020-07-07 at 15 09 14" src="https://user-images.githubusercontent.com/60126381/86715786-e8e77680-c063-11ea-861a-4aaa857500dc.png">

**Comment by lauriro** [comment]
Replacing css based indentation with text based indentation has been in todo list for some years.
