### ISSUE TITLE
Firefox rerenders page only after "inspect element"

### ISSUE THREAD

**Issue by volkov** [lauriro/json-lite#55]
Using Firefox 81.0.2 on ubuntu and json-lite 19.6.0

Sometimes json don't render completely. After pressing "Inspect element" json renders properly.
https://www.youtube.com/watch?v=YR5VA46PrLo

Any ideas why this could happen or how to debug it?
First time I noticed this behaviour in about month ago.

**Comment by lauriro** [comment]
According to the picture you are using different json viewer or Firefox native JSON viewer as in #12.

Native viewer can be disabled by toggling 'devtools.jsonview.enabled' flag in about:config page.

**Comment by volkov** [comment]
In screencast I'm using separate firefox profile with only json-lite (there is icon in right top corner) installed (with ubuntu dark theme) and devtools.jsonview.enabled set to false.

**Comment by lauriro** [comment]
Sry, responded too fast, colors were unusual for me.

**Comment by lauriro** [comment]
Seems to be a firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1599352
