### ISSUE TITLE
The plugin is great, can you get it on the Edge app store?

### ISSUE THREAD

**Issue by devin87** [lauriro/json-lite#57]
I can't access the Chrome Store here, and the extension installed from Edge supports syncing.

**Comment by lauriro** [comment]
https://microsoftedge.microsoft.com/addons/detail/json-lite/icjhnncodhmhckcdhhnbbhkhlbfggnnf

try it out and let me know, I have no access to windows to test

**Comment by devin87** [comment]
Yes, it's okay, thanks
