### ISSUE TITLE
Parse fail, when two consecutive slashes before the double quotes

### ISSUE THREAD

**Issue by ohyesx** [lauriro/json-lite#59]
Bug :
```
{
 "key1": "abc\\",
 "key2": 1234
}
```

the value `"abc\\"` will cause parsing error

**Comment by lauriro** [comment]
I was aware about this but somehow forgot before release, thank you.

**Comment by ohyesx** [comment]
thank you

I like this extension very much, it is the best JSON viewer ^^

Lauri Rooden <notifications@github.com> 於 2021年2月24日 週三 下午3:58寫道：

**Comment by lauriro** [comment]
fixed on 21.2.1, firefox already published, chrome and microsoft versions are in review
