### ISSUE TITLE
Add support for themes.

### ISSUE THREAD

**Issue by meltinglava** [lauriro/json-lite#6]
Would like if you can choose themes for the syntax and background.

**Comment by lauriro** [comment]
could you provide some good examples?

**Comment by meltinglava** [comment]
sry for taking so long to reply. 
Add support for different themes like 

- [Solarized](https://github.com/altercation/solarized)
- [Tomoorow](https://github.com/chriskempson/tomorrow-theme)
and many other popular ones

**Comment by luispabon** [comment]
Dracula theme is nice also. CSS lifted from a similar JSON extension in chrome:

```

**Comment by Cydfrey** [comment]
Hi,

I would like to add my two cents on this.
I don't really care for themes however I find that the default colors are not very easy to read (I use the default Firefox theme, white background). They are a bit too bright. So yeah, a way to change colors would be great.

Apart from that, love this add-on. Simple and lightweight, all that I need.

**Comment by lauriro** [comment]
Option to change colors is implemented in v17.12.2.

More predefined themes can be added when good examples found.

Depending your browser, FF and Chrome published, Opera awaiting moderation and port to Safari will take some more time.
