### ISSUE TITLE
Great product! Can you add line numbers please?

### ISSUE THREAD

**Issue by mlemmnapa** [lauriro/json-lite#8]
You've done a great job with the formatting. Would it be possible to add lines numbers on the left? Thank you!

**Comment by lauriro** [comment]
It takes some time. With current architecture this would be too great impact for performance, there are rewrite in progress that has to be completed first.

**Comment by jdegger** [comment]
The full CSS solution should not be that hard on performance:

https://codepen.io/elomatreb/pen/hbgxp

**Comment by boghyon** [comment]
What is actually the benefit of showing line numbers..? What's the use case?

**Comment by lauriro** [comment]
I can see a benefit to share a link to specific line in a large static json (like in github code).
Some can think they are just beautiful :)

Currently CSS solution is in use for other features.

**Comment by nguyenxndaidev** [comment]
> The full CSS solution should not be that hard on performance:
> 
> https://codepen.io/elomatreb/pen/hbgxp

Can css solution keep the correct line number when collapse items like below?
![image](https://user-images.githubusercontent.com/24372782/96998702-382eb580-1534-11eb-9815-4604c6b518c2.png)
